const simulacao = [
  {
    _id: "64a27d18c94927238c9cd9cf",
    botanicalName: "Borago officinalis",
    plantName: "Nova Planta",
    description:
      "Borage is an annual herb with hairy leaves and star-shaped blue flowers.",
    flowerColor: "Blue",
    foodNutrients: "Pollen",
    growthHabits: "Annual Herb",
    waterRequirements: "Moderate",
    nativeRegion: "Mediterranean",
    companionPlants: ["Tomatos", "Cucumber"],
    bloomingTimes: "Spring to Summer",
    imageUrl: "https://example.com/borage.jpg",
    plantHeight: "1 to 3 feet",
  },
  {
    _id: "64a27d18c94927238c9cd9cf",
    botanicalName: "Borago officinalis",
    plantName: "Borago",
    description:
      "Borage is an annual herb with hairy leaves and star-shaped blue flowers.",
    flowerColor: "Blue",
    foodNutrients: "Pollen",
    growthHabits: "Annual Herb",
    waterRequirements: "Moderate",
    nativeRegion: "Mediterranean",
    companionPlants: ["Tomatos", "Cucumber"],
    bloomingTimes: "Spring to Summer",
    imageUrl: "https://example.com/borage.jpg",
    plantHeight: "1 to 3 feet",
  },
  {
    _id: "64a27d18c94927238c9cd9cf",
    botanicalName: "Borago officinalis",
    plantName: "Borago",
    description:
      "Borage is an annual herb with hairy leaves and star-shaped blue flowers.",
    flowerColor: "Blue",
    foodNutrients: "Pollen",
    growthHabits: "Annual Herb",
    waterRequirements: "Moderate",
    nativeRegion: "Mediterranean",
    companionPlants: ["Tomatos", "Cucumber"],
    bloomingTimes: "Spring to Summer",
    imageUrl: "https://example.com/borage.jpg",
    plantHeight: "1 to 3 feet",
  },
  {
    _id: "64a27d18c94927238c9cd9cf",
    botanicalName: "Borago officinalis",
    plantName: "Borago",
    description:
      "Borage is an annual herb with hairy leaves and star-shaped blue flowers.",
    flowerColor: "Blue",
    foodNutrients: "Pollen",
    growthHabits: "Annual Herb",
    waterRequirements: "Moderate",
    nativeRegion: "Mediterranean",
    companionPlants: ["Tomatos", "Cucumber"],
    bloomingTimes: "Spring to Summer",
    imageUrl: "https://example.com/borage.jpg",
    plantHeight: "1 to 3 feet",
  },
  {
    _id: "64a27d18c94927238c9cd9cf",
    botanicalName: "Borago officinalis",
    plantName: "Borago",
    description:
      "Borage is an annual herb with hairy leaves and star-shaped blue flowers.",
    flowerColor: "Blue",
    foodNutrients: "Pollen",
    growthHabits: "Annual Herb",
    waterRequirements: "Moderate",
    nativeRegion: "Mediterranean",
    companionPlants: ["Tomatos", "Cucumber"],
    bloomingTimes: "Spring to Summer",
    imageUrl: "https://example.com/borage.jpg",
    plantHeight: "1 to 3 feet",
  },
  {
    _id: "64a27d18c94927238c9cd9cf",
    botanicalName: "Borago officinalis",
    plantName: "Borago",
    description:
      "Borage is an annual herb with hairy leaves and star-shaped blue flowers.",
    flowerColor: "Blue",
    foodNutrients: "Pollen",
    growthHabits: "Annual Herb",
    waterRequirements: "Moderate",
    nativeRegion: "Mediterranean",
    companionPlants: ["Tomatos", "Cucumber"],
    bloomingTimes: "Spring to Summer",
    imageUrl: "https://example.com/borage.jpg",
    plantHeight: "1 to 3 feet",
  },
  {
    _id: "64a27d18c94927238c9cd9cf",
    botanicalName: "Borago officinalis",
    plantName: "Borago",
    description:
      "Borage is an annual herb with hairy leaves and star-shaped blue flowers.",
    flowerColor: "Blue",
    foodNutrients: "Pollen",
    growthHabits: "Annual Herb",
    waterRequirements: "Moderate",
    nativeRegion: "Mediterranean",
    companionPlants: ["Tomatos", "Cucumber"],
    bloomingTimes: "Spring to Summer",
    imageUrl: "https://example.com/borage.jpg",
    plantHeight: "1 to 3 feet",
  },
  {
    _id: "64a27d18c94927238c9cd9cf",
    botanicalName: "Borago officinalis",
    plantName: "Borago",
    description:
      "Borage is an annual herb with hairy leaves and star-shaped blue flowers.",
    flowerColor: "Blue",
    foodNutrients: "Pollen",
    growthHabits: "Annual Herb",
    waterRequirements: "Moderate",
    nativeRegion: "Mediterranean",
    companionPlants: ["Tomatos", "Cucumber"],
    bloomingTimes: "Spring to Summer",
    imageUrl: "https://example.com/borage.jpg",
    plantHeight: "1 to 3 feet",
  },
  {
    _id: "64a27d18c94927238c9cd9cf",
    botanicalName: "Borago officinalis",
    plantName: "Borago",
    description:
      "Borage is an annual herb with hairy leaves and star-shaped blue flowers.",
    flowerColor: "Blue",
    foodNutrients: "Pollen",
    growthHabits: "Annual Herb",
    waterRequirements: "Moderate",
    nativeRegion: "Mediterranean",
    companionPlants: ["Tomatos", "Cucumber"],
    bloomingTimes: "Spring to Summer",
    imageUrl: "https://example.com/borage.jpg",
    plantHeight: "1 to 3 feet",
  },
  {
    _id: "64a27d18c94927238c9cd9cf",
    botanicalName: "Borago officinalis",
    plantName: "Borago",
    description:
      "Borage is an annual herb with hairy leaves and star-shaped blue flowers.",
    flowerColor: "Blue",
    foodNutrients: "Pollen",
    growthHabits: "Annual Herb",
    waterRequirements: "Moderate",
    nativeRegion: "Mediterranean",
    companionPlants: ["Tomatos", "Cucumber"],
    bloomingTimes: "Spring to Summer",
    imageUrl: "https://example.com/borage.jpg",
    plantHeight: "1 to 3 feet",
  },
  {
    _id: "64a27d18c94927238c9cd9cf",
    botanicalName: "Borago officinalis",
    plantName: "Borago",
    description:
      "Borage is an annual herb with hairy leaves and star-shaped blue flowers.",
    flowerColor: "Blue",
    foodNutrients: "Pollen",
    growthHabits: "Annual Herb",
    waterRequirements: "Moderate",
    nativeRegion: "Mediterranean",
    companionPlants: ["Tomatos", "Cucumber"],
    bloomingTimes: "Spring to Summer",
    imageUrl: "https://example.com/borage.jpg",
    plantHeight: "1 to 3 feet",
  },
];

export default simulacao;
